---
dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - nightly
env:
  - REMOVE_LOCALES=false
  - REMOVE_LOCALES=true
install:
  - pip install pyyaml coveralls flake8 flake8-import-order doc8 sphinx
  - pip install .
  - if [[ $REMOVE_LOCALES = "true" ]]; then sudo rm -rf /usr/lib/locale/*; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION != nightly ]]; then flake8 .; fi
  - doc8 $(git ls-files '*.rst')
  - yamllint --strict $(git ls-files '*.yaml' '*.yml')
  - coverage run --source=yamllint -m unittest discover
  - python setup.py build_sphinx
after_success:
  coveralls
