---
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - nightly
install:
  - pip install pyyaml coveralls flake8 flake8-import-order
  - if [[ $TRAVIS_PYTHON_VERSION != 2* ]]; then pip install sphinx; fi
  - pip install .
script:
  - flake8 .
  - yamllint --strict $(git ls-files '*.yaml' '*.yml')
  - coverage run --source=yamllint setup.py test
  - if [[ $TRAVIS_PYTHON_VERSION != 2* ]]; then
      python setup.py build_sphinx;
    fi
after_success:
  coveralls
