---
language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly
install:
  - pip install pyyaml flake8 flake8-import-order coveralls colorama
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
  - pip install .
script:
  - if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then flake8 .; fi
  - yamllint --strict $(git ls-files '*.yaml' '*.yml')
  - coverage run --source=yamllint setup.py test
after_success:
  coveralls
