---
dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - nightly
env:
  - REMOVE_LOCALES=false
  - REMOVE_LOCALES=true
install:
  - pip install tox-travis
  - if [[ $REMOVE_LOCALES = "true" ]]; then sudo rm -rf /usr/lib/locale/*; fi
script:
  - tox
after_success:
  coveralls
